algoritmo "Diagrama"

var
N1, N2, N3, N4: inteiro
NQ1, NQ2, NQ3, NQ4: inteiro
Total: inteiro

inicio
escreval ("Digite o valor do N1: ")
Leia (N1)
NQ1 <- (N1*N1)

escreval ("Digite o valor do N2: ")
Leia (N2)
NQ2 <- (N2*N2)

escreval ("Digite o valor do N3: ")
Leia (N3)
NQ3 <- (N3*N3)

escreval ("Digite o valor do N4: ")
Leia (N4)
NQ4 <- (N4*N4)

escreval ("Soma dos quadrados igual a: ")
Total <-(NQ1+NQ2+NQ3+NQ4)

escreva (Total)

fimalgoritmo
